## Problem Statement 

| Size (sqft) | Number of Bedrooms  | Number of floors | Age of  Home | Price (1000s dollars)  |   
| ----------------| ------------------- |----------------- |--------------|-------------- |  
| 2104            | 5                   | 1                | 45           | 460           |  
| 1416            | 3                   | 2                | 40           | 232           |  
| 852             | 2                   | 1                | 35           | 178           | 

Given above data, train a linear regrission model to predict a new house price given its size, #bedrooms, #floors, and Age of house.

with `w_init` = [ 0.39133535, 18.75376741, -53.36032453, -26.42131618], and `b_init` = 785.1811367994083
>**Note**: Implementation of cost func, and gradiant decent is required

### solution


First we represent the given data into numpy array and vector, `X_train` is a matrix of size `3x4`, contains 3 training examples and 4 features ber each training example. And `y_train` for target values ber each training example.

In [1]:
import numpy as np

In [5]:
X_train = np.array([[2104, 5, 1, 45],[1416, 3, 2, 40],[852, 2, 1, 35]])
y_train = np.array([460, 232, 178])
print(X_train)
print(X_train.shape)
print(y_train)
print(y_train.shape)

[[2104    5    1   45]
 [1416    3    2   40]
 [ 852    2    1   35]]
(3, 4)
[460 232 178]
(3,)


>**Note**: `y_train` is a column vector

We will make use of straight line model in its vector form like:
   $f_{\mathbf{w},b}(\mathbf{x}^{(i)}) = \mathbf{w}^{(i)} \cdot \mathbf{x}^{(i)} + b \tag{1}$ 

where $\mathbf{x}^{(i)}$ is input features - vector (`X_train[i]`) for $i^{th}$ training example, and $\mathbf{w}$, $b$ are the model parameters.
$\mathbf{w}^{(i)}$ is a vector, while $b$ is a scalar

#### Model implementation

In [12]:
def predict(x, w, b):
    """ 
    predict using linear regression
    x is numpy ndarray represents input features
    w is numpy ndarray (model parameters)
    b is scalar (model parameter)
    
    returns p (scalar): prediction
    """
    try:
        p = np.dot(x, w) + b
    except Exception as e:
        print(e)
    return p

In [7]:
# taking w_init, b_init 
b_init = 785.1811367994083
w_init = np.array([ 0.39133535, 18.75376741, -53.36032453, -26.42131618])

In [17]:
# make a prediction on first training example to test the model
x_vec = X_train[0]
print(x_vec)
prediction = predict(x_vec, w_init, b_init)
print(prediction)

[2104    5    1   45]
459.9999976194083


The result is near to the actual value

#### Computing cost

Let the cost func be the squared error func:

$$J(\mathbf{w},b) = \frac{1}{2m} \sum\limits_{i = 0}^{m-1} (f_{\mathbf{w},b}(\mathbf{x}^{(i)}) - y^{(i)})^2 \tag{2}$$ 

In [20]:
def compute_cost(X, y, w, b):
    """
    Args:
      X (ndarray (m,n)): Data, m examples with n features
      y (ndarray (m,)) : target values
      w (ndarray (n,)) : model parameters  
      b (scalar)       : model parameter
      
    Returns:
      cost (scalar): cost
    """
    m = X.shape[0]
    cost = 0.0
    for i in range(m):
        f_wb_i = np.dot(X[i], w) + b
        cost = cost + (f_wb_i - y[i])**2
    cost = cost/(2*m)
    return cost

In [21]:
cost = compute_cost(X_train, y_train, w_init, b_init)
print(cost)

1.5578904428966628e-12
